### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by MggMuggins** [Longhanks/qlift-swift-example#1]
Realizing that this is seriously new, I'm wondering how to build under linux. ```swift build``` grabbed qlift like it should have, but I'm not sure how to link with CQlift. Any advice?

Also, kudos to you for doing a swift binding for Qt. The guys (myself included I guess) over at the [Artemis project](https://artemis-project.github.io) are interested in what you're doing here. I think some of us would be willing to help out. Marquis may contact you later.

**Comment by alicerunsonfedora** [comment]
Hi @Longhanks ,

We’re definitely excited to see a Qt binding for Swift! I’m the head of the [Artemis Project](http://artemis-project.github.io), and we’re currently discussing some things for the future regarding our desktop shell, which may be merged from two projects into one. One of the topics that came up was a shell written in Qt and Swift under Wayland (thanks to a combo between it, D, and Swift). When we saw this repo and its project, a few of us definitely got excited. We’re interested to see what comes out of this and hope to work with you in the future on making this as successful as possible.

I’m currently using Riot, but there’s other ways to get in touch with [me](http://www.marquiskurt.tk/contact/) and the [project team](http://artemis-project.github.io/contrib/); let’s discuss this further.

**Comment by Longhanks** [comment]
CQlift is a modulemap wrapping [qlift-c-api](https://github.com/Longhanks/qlift-c-api). CQlift thus needs qlift-c-api installed, on Linux, it is expected to reside at `/usr/lib/libqlift-c-api.so`, with the public header at `/usr/include/qlift-c-api.h` and the private headers at `/usr/include/qlift-c-api/`.

There is two ways to install qlift-c-api: On Arch Linux, you can use the instructions provided at [pacman-qlift](https://github.com/Longhanks/pacman-qlift) to download prebuilt binaries. You will also find a PKGBUILD there.
The other option is to build directly from source. The standard procedure would be:

1. Cloning qlift-c-api, `cd` to cloned directory
2. `mkdir build && cd build`
3. `cmake .. -DCMAKE_INSTALL_PREFIX=/usr`
4. `sudo make install`

Let me know if you encounter any problems.

By the way, thanks for the appreciation! Bear in mind that this is just a "fun" project of mine. Since Swift cannot interop with C++ easily, everything must go through the C bridge, which makes things pretty complicated. I'm not sure how far this project can go before hitting the limitations of this Swift -> C -> C++ bridge. And of course, it's in a very early stage, and there's not much useful things you can do.

**Comment by MggMuggins** [comment]
Thanks! That arch package makes life so much easier. I'll try that first, but would installing in /usr/local work too?

Honestly I'd be interested in your C bridge even if the swift stopped being a priority, since so many other languages (namely D) can interface with C so easily. Let us know if we can do anything for you at all!

**Comment by Longhanks** [comment]
Installing to /usr/local will work if you create a separate modulemap package analog to CQlift. Edit the module.modulemap file to point to the new location of qlift-c-api. Create a release and edit Package.swift of qlift to depend on your new modulemap. Make sure /usr/local is in your LD_LIBRARY_PATH when linking. That should be it!

**Comment by MggMuggins** [comment]
Thanks. The Aur PKGBUILD worked like a charm. I'm still getting a build error though:
```
./qlift-swift-example/.build/checkouts/qlift--<Large string of digits>/Sources/QSpacerItem.swift:9:20: error: use of unresolved identifier 'QSpacerItem_new'
```
There are more errors at 4:12 and 14:13.
This is definitely an issue with qlift, not this repo, so I can move this if you'd like.

**Comment by Longhanks** [comment]
Yep, sorry, I had to update the binary package to 0.0.15. Could you give it another shot?

**Comment by MggMuggins** [comment]
Which, the C or the swift?

**Comment by Longhanks** [comment]
The qlift-c-api package installable via pacman if you followed the instructions at [pacman-qlift](https://github.com/Longhanks/pacman-qlift). You can also retry the PKGBUILD, I updated it to fetch version 0.0.15 (which introduces QSpacerItem, which this project uses).

**Comment by MggMuggins** [comment]
I used the PKGBUILD instead of the pacman repo. I'll retry that.

There we go. Thanks much!
